# Generated by Django 5.1.2 on 2024-11-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_avatar_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='Topics',
        ),
    ]
