# Generated by Django 5.1.2 on 2024-11-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_messages_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='assets/avatar.svg', null=True, upload_to=''),
        ),
    ]
